name: 'Restore kernel cache'
description: 'Restore a previously built kernel cache, failing if not available'
inputs:
  repo-name:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Get hash from repo/branch
      run: echo "SCHED_EXT_KERNEL_COMMIT=$(jq -r '."${{ inputs.repo-name }}".commitHash' kernel-versions.json)" >> $GITHUB_ENV
      shell: bash

    - name: Load cache
      uses: actions/cache/restore@v4
      with:
        fail-on-cache-miss: true
        key: kernel-build-${{ env.SCHED_EXT_KERNEL_COMMIT }}-7
        path:  |
          linux/arch/x86/boot/bzImage
          linux/usr/include
          linux/**/*.h
